### ISSUE TITLE
Sometimes, when click edit profile, crash

### ISSUE THREAD

**Issue by PascalSun** [PascalSun/sportpartner#4]
Sometimes, when click on the edit profile with high frequency, then program will crash, and 

```
Users/pascal_sun/Google Drive/workplace/Github/MIT-year2/AigleWeb/Project2/sportpartner/node_modules/node-geocoder/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

TypeError: Cannot read property '0' of undefined
    at Geocoder.<anonymous> (/Users/pascal_sun/Google Drive/workplace/Github/MIT-year2/AigleWeb/Project2/sportpartner/app_server/controller/user.js:142:29)
    at Geocoder.tryCatcher (/Users/pascal_sun/Google Drive/workplace/Github/MIT-year2/AigleWeb/Project2/sportpartner/node_modules/node-geocoder/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.errorAdapter [as _rejectionHandler0] (/Users/pascal_sun/Google Drive/workplace/Github/MIT-year2/AigleWeb/Project2/sportpartner/node_modules/node-geocoder/node_modules/bluebird/js/release/nodeify.js:35:34)
    at Promise._settlePromise (/Users/pascal_sun/Google Drive/workplace/Github/MIT-year2/AigleWeb/Project2/sportpartner/node_modules/node-geocoder/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/Users/pascal_sun/Google Drive/workplace/Github/MIT-year2/AigleWeb/Project2/sportpartner/node_modules/node-geocoder/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/pascal_sun/Google Drive/workplace/Github/MIT-year2/AigleWeb/Project2/sportpartner/node_modules/node-geocoder/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/pascal_sun/Google Drive/workplace/Github/MIT-year2/AigleWeb/Project2/sportpartner/node_modules/node-geocoder/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/pascal_sun/Google Drive/workplace/Github/MIT-year2/AigleWeb/Project2/sportpartner/node_modules/node-geocoder/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/pascal_sun/Google Drive/workplace/Github/MIT-year2/AigleWeb/Project2/sportpartner/node_modules/node-geocoder/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
```

**Comment by PascalSun** [comment]
Show up 2 times, have not find why

**Comment by PascalSun** [comment]
Maybe because the geocode error have not been caught, have add 
```
if(err) throw err;
```
Let's see what happen next

**Comment by PascalSun** [comment]
There are two more places to throw the err
which have not added before
